name: Deploy AWS Lambda

on:
  # the 1st condition
  workflow_run:
    workflows: ["Create AWS Lambda"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Lambda
        run: |
          echo "Deploying Lambda..."
